excluded:
  - Carthage
  - Pods
  - Templates
#  - Source/ExcludedFolder
#  - Source/ExcludedFile.swift
#  - Source/*/ExcludedFile.swift
opt_in_rules:
  - anyobject_protocol
  - attributes
  - closure_body_length
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_first_not_nil
  - convenience_type
  - discouraged_object_literal
  - empty_count
  - empty_string
  - explicit_enum_raw_value
  - explicit_init
  - explicit_self
  - fatal_error_message
  - file_name
  - first_where
  - force_unwrapping
  - function_default_parameter_at_end
  - identical_operands
  - implicit_return
  - joined_default_parameter
  - last_where
  - legacy_random
  - let_var_whitespace
  - literal_expression_end_indentation
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefixed_toplevel_constant
  - private_action
  - private_outlet
  - prohibited_super_call
  - sorted_first_last
  - toggle_bool
  - unused_import
  - unused_private_declaration
  - vertical_parameter_alignment_on_call
disabled_rules:
  - multiple_closures_with_trailing_closure
  - nesting
  - private_over_fileprivate
  - private_unit_test
  - redundant_string_enum_value
  - trailing_whitespace
  - vertical_whitespace
anyobject_protocol:
  severity: error
attributes:
  severity: warning
block_based_kvo:
  severity: warning
class_delegate_protocol:
  severity: error
closing_brace:
  severity: warning
closure_body_length:
  warning: 20
  error: 100
closure_end_indentation:
  severity: warning
closure_parameter_position:
  severity: warning
closure_spacing:
  severity: warning
collection_alignment:
  severity: warning
colon:
  severity: warning
comma:
  severity: warning
compiler_protocol_init:
  severity: error
conditional_returns_on_newline:
  severity: warning
contains_over_first_not_nil:
  severity: error
control_statement:
  severity: warning
convenience_type:
  severity: error
custom_rules:
  severity: warning
cyclomatic_complexity:
  warning: 20
  error: 100
discarded_notification_center_observer:
  severity: error
discouraged_direct_init:
  severity: error
discouraged_object_literal:
  severity: error
dynamic_inline:
  severity: error
empty_count:
  severity: error
empty_enum_arguments:
  severity: warning
empty_parameters:
  severity: warning
empty_parentheses_with_trailing_closure:
  severity: warning
empty_string:
  severity: error
explicit_enum_raw_value:
  severity: error
explicit_init:
  severity: error
explicit_self:
  severity: error
fatal_error_message:
  severity: error
file_length:
  warning: 1000
  error: 1500
file_name:
  severity: warning
first_where:
  severity: error
for_where:
  severity: error
force_cast:
  severity: error
force_try:
  severity: error
force_unwrapping:
  severity: error
function_body_length:
  warning: 200
  error: 300
function_default_parameter_at_end:
  severity: error
function_parameter_count:
  warning: 10
  error: 15
generic_type_name:
  severity: error
identical_operands:
  severity: error
identifier_name:
  min_length:
    error: 3
  max_length:
    warning: 40
  excluded:
    - i
    - j
    - x
    - y
    - ad
    - db
    - id
    - my
    - nc
    - ok
    - to
    - vc
    - vm
    - _input
    - _interactor
    - _mainController
    - _output
    - _presenter
    - _repository
    - _router
    - _view
    - _viewModel
implicit_getter:
  severity: warning
implicit_return:
  severity: warning
inert_defer:
  severity: error
joined_default_parameter:
  severity: error
large_tuple:
  warning: 4
  error: 6
last_where:
  severity: error
leading_whitespace:
  severity: warning
legacy_cggeometry_functions:
  severity: error
legacy_constant:
  severity: error
legacy_constructor:
  severity: error
legacy_hashing:
  severity: error
legacy_nsgeometry_functions:
  severity: error
legacy_random:
  severity: error
let_var_whitespace:
  severity: warning
line_length:
  warning: 500
  error: 700
literal_expression_end_indentation:
  severity: warning
lower_acl_than_parent:
  severity: error
mark:
  severity: warning
multiline_arguments:
  severity: warning
multiline_arguments_brackets:
  severity: warning
multiline_function_chains:
  severity: warning
multiline_literal_brackets:
  severity: warning
multiline_parameters:
  severity: warning
multiline_parameters_brackets:
  severity: warning
nesting:
  severity: error
no_extension_access_modifier:
  severity: error
no_fallthrough_only:
  severity: error
notification_center_detachment:
  severity: error
number_separator:
  severity: warning
opening_brace:
  severity: warning
operator_usage_whitespace:
  severity: warning
operator_whitespace:
  severity: warning
overridden_super_call:
  severity: error
pattern_matching_keywords:
  severity: error
prefixed_toplevel_constant:
  severity: warning
private_action:
  severity: error
private_outlet:
  severity: error
prohibited_super_call:
  severity: error
protocol_property_accessors_order:
  severity: error
redundant_discardable_let:
  severity: warning
redundant_objc_attribute:
  severity: warning
redundant_optional_initialization:
  severity: warning
redundant_set_access_control:
  severity: warning
redundant_string_enum_value:
  severity: warning
redundant_void_return:
  severity: warning
return_arrow_whitespace:
  severity: warning
shorthand_operator:
  severity: warning
sorted_first_last:
  severity: error
sorted_imports:
  severity: warning
statement_position:
  severity: warning
switch_case_alignment:
  severity: warning
syntactic_sugar:
  severity: error
todo:
  severity: warning
toggle_bool:
  severity: error
trailing_comma:
  severity: warning
trailing_newline:
  severity: warning
trailing_semicolon:
  severity: warning
type_body_length:
  warning: 300
  error: 400
type_name:
  severity: error
unneeded_break_in_switch:
  severity: warning
unused_closure_parameter:
  severity: warning
unused_control_flow_label:
  severity: error
unused_enumerated:
  severity: warning
unused_import:
  severity: error
unused_optional_binding:
  severity: error
unused_private_declaration:
  severity: error
valid_ibinspectable:
  severity: error
vertical_parameter_alignment:
  severity: warning
vertical_parameter_alignment_on_call:
  severity: warning
vertical_whitespace_closing_braces:
  severity: warning
void_return:
  severity: warning
weak_delegate:
  severity: error
