name: CI

on: [pull_request]

jobs:
  danger:
    runs-on: ubuntu-latest
    name: "Run Danger"
    if: github.ref == 'refs/heads/develop'
    steps:
      - uses: actions/checkout@v1
      - name: Danger
        uses: danger/swift@3.3.0
        with:
            args: --failOnErrors --no-publish-check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  test:
    runs-on: macOS-latest
    if: github.ref == 'refs/heads/develop'
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: xcodebuild -project 'News.xcodeproj' -scheme 'News' -destination 'platform=iOS Simulator,name=iPhone 8' test
    - name: Build App
      run: xcodebuild -project 'News.xcodeproj' -scheme 'News' -destination 'generic/platform=iOS' -configuration Release build CODE_SIGNING_ALLOWED=NO
