name: CI

on: [pull_request]

jobs:
  test:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - name: "Run tests"
      run: xcodebuild -project 'News.xcodeproj' -scheme 'News' -destination 'platform=iOS Simulator,name=iPhone 8' test
    - name: Build App
      run: xcodebuild -project 'News.xcodeproj' -scheme 'News' -destination 'generic/platform=iOS' -configuration Release build CODE_SIGNING_ALLOWED=NO
